import { BriefcaseBusiness, GraduationCap, Trophy } from 'lucide-react'
import { skillGroups } from '../data/portfolio'

export function AboutPage() {
  return <>
    <section className="page-hero"><span className="eyebrow">About / Pallavi</span><h1>Curious by nature.<br /><em>Consistent</em> by practice.</h1><p>An AI/ML student, software builder, and competitive athlete—learning to solve hard problems with clarity and discipline.</p></section>
    <section className="section about-section"><div className="about-grid"><div className="about-image"><img src="/assets/pallavi-campus.jpg" alt="Pallavi standing on her college campus" /><span>Global Academy of Technology · Bengaluru</span></div><div className="about-copy"><p className="lead">I enjoy working where software engineering meets intelligent systems—building products that are thoughtful, practical, and easy to use.</p><p>My coursework and projects have given me a strong base in programming, machine learning, computer vision, databases, and core computer science. At BHEL, I applied that foundation to a full-stack employee incentive platform with secure, role-based workflows.</p><p>Outside technology, competitive netball has shaped how I work: communicate clearly, stay composed, and keep showing up for the team.</p><div className="principles"><span>01. Learn deeply</span><span>02. Build clearly</span><span>03. Improve continuously</span></div></div></div></section>
    <section className="section experience-section"><div className="section-heading"><span className="eyebrow">01 / Experience & education</span><h2>Learning by shipping.</h2></div><div className="experience-grid"><article className="experience-card"><div className="experience-mark"><BriefcaseBusiness size={25} /></div><div><span className="experience-type">Industry experience</span><h3>Software Developer Intern</h3><p className="company">BHEL · Bengaluru</p><ul><li>Built a full-stack application to automate employee incentive calculations and replace manual record maintenance.</li><li>Designed dedicated Admin and Employee dashboards with clear role-based workflows.</li><li>Implemented secure authentication, authorization, and role-based access control.</li></ul></div></article><div className="education-stack"><div className="education-card primary"><GraduationCap size={24} /><div><span>2023 — 2027</span><h3>B.E. Computer Science & Engineering</h3><p>Artificial Intelligence & Machine Learning<br />Global Academy of Technology</p></div><strong>8.02</strong></div><div className="education-card"><span>2023</span><div><h3>Pre-University</h3><p>RNS Composite PU College</p></div><strong>89%</strong></div><div className="education-card"><span>2021</span><div><h3>Secondary School</h3><p>The New Cambridge High School</p></div><strong>90%</strong></div></div></div></section>
    <section className="section skills-section"><div className="skills-intro"><span className="eyebrow">02 / Toolkit</span><h2>A growing technical foundation.</h2><p>Comfortable moving from problem definition and data exploration to implementation and interface.</p></div><div className="skill-list">{skillGroups.map((group,index)=><div className="skill-row" key={group.title}><span>0{index+1}</span><h3>{group.title}</h3><p>{group.value}</p></div>)}</div></section>
    <section className="section achievements-section"><div className="section-heading section-heading-row"><div><span className="eyebrow">03 / Beyond code</span><h2>Competitive on court.<br />Collaborative everywhere.</h2></div><Trophy className="trophy-icon" size={58} strokeWidth={1.2}/></div><div className="achievement-list"><article><span>2025</span><div><h3>All India Inter University Netball Tournament</h3><p>Represented Karnataka</p></div><strong>National</strong></article><article><span>2025</span><div><h3>VTU State-level Netball Tournament</h3><p>Winner</p></div><strong>State</strong></article><article><span>2023</span><div><h3>Under-19 National Netball Championship</h3><p>Represented Karnataka · Runner-up</p></div><strong>National</strong></article></div></section>
  </>
}
